version: '3.8'

services:
  backend:
    build: .
    container_name: backend_api
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "7000:7000"

  db:
    image: postgres:14-alpine
    container_name: db
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
