# Generated by Django 4.1.1 on 2022-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField(db_index=True, unique=True)),
                ('alias_url', models.CharField(max_length=60, unique=True)),
                ('ip_user', models.CharField(max_length=30)),
                ('visited', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['origin_url'],
            },
        ),
    ]
