# Generated by Django 4.1.1 on 2022-09-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedurls',
            name='alias_url',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='generatedurls',
            name='origin_url',
            field=models.URLField(unique=True),
        ),
    ]
